"""Report fields."""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

UTC = timezone.utc


def _parse_date(date: str) -> datetime:
    """Parse date.

    Args:
        date: Date string.

    Returns:
        Parsed date.
    """
    return datetime.strptime(date, "%m/%d/%Y %H:%M:%S").replace(tzinfo=UTC)


analytics_type_mappings = {
    # --- Dimensions ---
    "Adset": {"type": "string"},
    "AdsetId": {"type": "string"},
    "Campaign": {"type": "string"},
    "CampaignId": {"type": "string"},
    "Advertiser": {"type": "string"},
    "AdvertiserId": {"type": "string"},
    "Category": {"type": "string"},
    "CategoryId": {"type": "string"},
    "Ad": {"type": "string"},
    "AdId": {"type": "string"},
    "Coupon": {"type": "string"},
    "CouponId": {"type": "string"},
    "MarketingObjective": {"type": "string"},
    "MarketingObjectiveId": {"type": "string"},
    "Channel": {"type": "string"},
    "ChannelId": {"type": "string"},
    "Goal": {"type": "string"},
    "AdChannel": {"type": "string"},
    "SocialPlatform": {"type": "string"},
    "OS": {"type": "string"},
    "Os": {"type": "string"},
    "Device": {"type": "string"},
    "ResultType": {"type": "string"},
    "Currency": {"type": "string"},
    # --- Time Dimensions ---
    "Year": {"type": "string", "format": "date"},
    "Month": {"type": "string", "format": "date"},
    "Week": {"type": "string", "format": "date"},
    "Day": {"type": "string", "format": "date"},
    "Hour": {"type": "string", "format": "date-time"},
    # --- Core Metrics ---
    "Clicks": {"type": "integer"},
    "Displays": {"type": "integer"},
    "Visits": {"type": "integer"},
    "VisitsPV1D": {"type": "integer"},
    "QualifiedVisits": {"type": "integer"},
    "AdvertiserCost": {"type": "number"},
    "ClickThroughRate": {"type": "number"},
    "BounceRate": {"type": "number"},
    # --- Display / Reach Metrics ---
    "ExposedUsers": {"type": "integer"},
    "Audience": {"type": "integer"},
    "Reach": {"type": "integer"},
    "PotentialDisplays": {"type": "integer"},
    "ViewableDisplays": {"type": "integer"},
    "NonViewableDisplays": {"type": "integer"},
    "UntrackableDisplays": {"type": "integer"},
    "InvalidDisplays": {"type": "integer"},
    "InvalidClicks": {"type": "integer"},
    "Frequency": {"type": "number"},
    "OverallCompetitionWin": {"type": "number"},
    # --- Video Metrics ---
    "VideoStarted": {"type": "integer"},
    "VideoFirstQuartile": {"type": "integer"},
    "VideoMidpoint": {"type": "integer"},
    "VideoThirdQuartile": {"type": "integer"},
    "VideoCompleted": {"type": "integer"},
    "VideoAvoc": {"type": "integer"},
    "VideoStartRate": {"type": "number"},
    "VideoCompletionRate": {"type": "number"},
    "VideoAverageViewRate": {"type": "number"},
    "VideoCpv": {"type": "number"},
    "VideoCpcv": {"type": "number"},
    # --- App Metrics ---
    "AppInstalls": {"type": "integer"},
    "AppInstallsPcPv": {"type": "integer"},
    "InstallRate": {"type": "number"},
    "InstallRatePcPv": {"type": "number"},
    "CostPerInstall": {"type": "number"},
    "CostPerInstallPcPv": {"type": "number"},
    # --- Cost Rates ---
    "Cpc": {"type": "number"},
    "ECpc": {"type": "number"},
    "ECpm": {"type": "number"},
    "CostPerVisit": {"type": "number"},
    "CostPerVisitPV1D": {"type": "number"},
    "CostPerQualifiedVisit": {"type": "number"},
    # --- Dynamic Rate/Currency Metric Groups (All Decimals) ---
    **{
        k: {"type": "number"}
        for k in [
            "RevenueGeneratedClientAttribution",
            "RevenueGeneratedAllClientAttribution",
            "RevenueGeneratedPc30d",
            "RevenueGeneratedAllPc30d",
            "RevenueGeneratedPv24h",
            "RevenueGeneratedAllPv24h",
            "RevenueGeneratedPc30dPv24h",
            "RevenueGeneratedAllPc30dPv24h",
            "RevenueGeneratedPc1d",
            "RevenueGeneratedAllPc1d",
            "RevenueGeneratedPc7d",
            "RevenueGeneratedAllPc7d",
            "RevenueGeneratedPc30Pv24",
            "RevenueGeneratedAllPc30Pv24",
            "RevenueGeneratedPc7dPv24",
            "RevenueGeneratedAllPc7dPv24",
            "RevenueGeneratedLc",
            "RevenueGeneratedAllLc",
            "RevenueGeneratedOfflinePc",
            "RevenueGeneratedOfflinePv",
            "RevenueGeneratedOfflinePc30d",
            "RevenueGeneratedOfflinePv24h",
            "OmnichannelRevenuePc30d",
            "OmnichannelRevenueAllPc30d",
            "OmnichannelRevenuePv24h",
            "OmnichannelRevenueAllPv24h",
            "OmnichannelRevenueClientAttribution",
            "OrderValuePi",
            "PostInstallOrderValue",
            "AdvertiserValue",
            "AdvertiserAllValue",
            "CostOfAdvertiserValue",
            "CostOfAdvertiserValueAll",
        ]
    },
    **{
        k: {"type": "number"}
        for k in [
            "RoasPc30d",
            "RoasAllPc30d",
            "RoasPv24h",
            "RoasAllPv24h",
            "RoasPc7d",
            "RoasAllPc7d",
            "RoasPc1d",
            "RoasAllPc1d",
            "RoasPc30dPv24h",
            "RoasAllPc30dPv24h",
            "RoasPc30Pv24",
            "RoasAllPc30Pv24",
            "RoasPc7dPv24",
            "RoasAllPc7dPv24",
            "RoasClientAttribution",
            "RoasAllClientAttribution",
            "RoasPc30dClientAttribution",
            "RoasAllPc30dClientAttribution",
            "OmnichannelRoasPc30d",
            "OmnichannelRoasAllPc30d",
            "OmnichannelRoasPv24h",
            "OmnichannelRoasAllPv24h",
            "OmnichannelRoasClientAttribution",
            "PostInstallRoas",
            "RoasOfflinePc30d",
            "RoasOfflinePv24h",
            "ReturnOnAdvertisingSpendingClientAttribution",
            "ReturnOnAdvertisingSpendingAllClientAttribution",
            "ReturnOnAdvertiserSpendingPi",
            "ReturnOnAdvertiserSpendingOfflinePc",
            "ReturnOnAdvertiserSpendingOfflinePv",
        ]
    },
    **{
        k: {"type": "number"}
        for k in [
            "CostPerOrderPc30d",
            "CostPerOrderAllPc30d",
            "CostPerOrderPv24h",
            "CostPerOrderAllPv24h",
            "CostPerOrderPc7d",
            "CostPerOrderAllPc7d",
            "CostPerOrderPc1d",
            "CostPerOrderAllPc1d",
            "CostPerOrderPc30dPv24h",
            "CostPerOrderAllPc30dPv24h",
            "CostPerOrderPc30Pv24",
            "CostPerOrderAllPc30Pv24",
            "CostPerOrderPc7dPv24",
            "CostPerOrderAllPc7dPv24",
            "CostPerOrderClientAttribution",
            "CostPerOrderAllClientAttribution",
            "CostPerOrderPc30dClientAttribution",
            "CostPerOrderAllPc30dClientAttribution",
            "CostPerOrderPi",
            "PostInstallCostPerOrder",
        ]
    },
    **{
        k: {"type": "number"}
        for k in [
            "ConversionRatePc30d",
            "ConversionRateAllPc30d",
            "ConversionRatePv24h",
            "ConversionRateAllPv24h",
            "ConversionRatePc7d",
            "ConversionRateAllPc7d",
            "ConversionRatePc1d",
            "ConversionRateAllPc1d",
            "ConversionRatePc30dPv24h",
            "ConversionRateAllPc30dPv24h",
            "ConversionRatePc30Pv24",
            "ConversionRateAllPc30Pv24",
            "ConversionRatePc7dPv24",
            "ConversionRateAllPc7dPv24",
            "ConversionRateClientAttribution",
            "ConversionRateAllClientAttribution",
            "ConversionRatePc30dClientAttribution",
            "ConversionRateAllPc30dClientAttribution",
            "ConversionRatePiPcPv",
            "PostInstallConversionRate",
        ]
    },
    **{
        k: {"type": "number"}
        for k in [
            "ECosPc30d",
            "ECosAllPc30d",
            "ECosPv24h",
            "ECosAllPv24h",
            "ECosPc7d",
            "ECosAllPc7d",
            "ECosPc1d",
            "ECosAllPc1d",
            "ECosPc30dPv24h",
            "ECosAllPc30dPv24h",
            "ECosPc30Pv24",
            "ECosAllPc30Pv24",
            "ECosPc7dPv24",
            "ECosAllPc7dPv24",
            "ECosClientAttribution",
            "ECosAllClientAttribution",
            "ECosPc30dClientAttribution",
            "ECosAllPc30dClientAttribution",
            "CostOfSalePi",
            "PostInstallCostOfSale",
        ]
    },
    **{
        k: {"type": "number"}
        for k in [
            "AverageCartPc30d",
            "AverageCartAllPc30d",
            "AverageCartPv24h",
            "AverageCartAllPv24h",
            "AverageCartPc7d",
            "AverageCartAllPc7d",
            "AverageCartPc1d",
            "AverageCartAllPc1d",
            "AverageCartPc30dPv24h",
            "AverageCartAllPc30dPv24h",
            "AverageCartPc30Pv24",
            "AverageCartAllPc30Pv24",
            "AverageCartPc7dPv24",
            "AverageCartAllPc7dPv24",
            "AverageCartClientAttribution",
            "AverageCartAllClientAttribution",
            "AverageCartPc30dClientAttribution",
            "AverageCartAllPc30dClientAttribution",
        ]
    },
    **{
        k: {"type": "number"}
        for k in [
            "CacPc30d",
            "CacPv24h",
            "CacPc7d",
            "CacPc1d",
            "CacPv7d",
            "CacPv14d",
            "CacPv30d",
            "CacPc30Pv24h",
            "CacPc7dPv24h",
            "CacLc30d",
            "CacClientAttribution",
        ]
    },
    # --- Dynamic Sales Metric Groups (All Integers) ---
    **{
        k: {"type": "integer"}
        for k in [
            "SalesClientAttribution",
            "SalesAllClientAttribution",
            "SalesPc30d",
            "SalesAllPc30d",
            "SalesPv24h",
            "SalesAllPv24h",
            "SalesPc30dPv24h",
            "SalesAllPc30dPv24h",
            "SalesPc1d",
            "SalesAllPc1d",
            "SalesPc7d",
            "SalesAllPc7d",
            "SalesPc30Pv24",
            "SalesAllPc30Pv24",
            "SalesPc7dPv24",
            "SalesAllPc7dPv24",
            "SalesLc",
            "SalesAllLc",
            "SalesPiPc",
            "SalesPiPv",
            "SalesPiPcPv",
            "PostInstallSales",
            "SalesOfflinePc",
            "SalesOfflinePv",
            "SalesOfflinePc30d",
            "SalesOfflinePv24h",
            "SalesPc30dClientAttribution",
            "SalesAllPc30dClientAttribution",
            "OmnichannelSalesPc30d",
            "OmnichannelSalesAllPc30d",
            "OmnichannelSalesPv24h",
            "OmnichannelSalesAllPv24h",
            "OmnichannelSalesClientAttribution",
        ]
    },
}


value_func_mapping: dict[str, Callable[[str], Any]] = {
    "Date": _parse_date,
    # --- Core Metrics ---
    "Clicks": int,
    "Displays": int,
    "Visits": int,
    "VisitsPV1D": int,
    "QualifiedVisits": int,
    "AdvertiserCost": Decimal,
    "ClickThroughRate": Decimal,
    "BounceRate": Decimal,
    # --- Display / Reach Metrics ---
    "ExposedUsers": int,
    "Audience": int,
    "Reach": int,
    "PotentialDisplays": int,
    "ViewableDisplays": int,
    "NonViewableDisplays": int,
    "UntrackableDisplays": int,
    "InvalidDisplays": int,
    "InvalidClicks": int,
    "Frequency": Decimal,
    "OverallCompetitionWin": Decimal,
    # --- Video Metrics ---
    "VideoStarted": int,
    "VideoFirstQuartile": int,
    "VideoMidpoint": int,
    "VideoThirdQuartile": int,
    "VideoCompleted": int,
    "VideoAvoc": int,
    "VideoStartRate": Decimal,
    "VideoCompletionRate": Decimal,
    "VideoAverageViewRate": Decimal,
    "VideoCpv": Decimal,
    "VideoCpcv": Decimal,
    # --- App Metrics ---
    "AppInstalls": int,
    "AppInstallsPcPv": int,
    "InstallRate": Decimal,
    "InstallRatePcPv": Decimal,
    "CostPerInstall": Decimal,
    "CostPerInstallPcPv": Decimal,
    # --- Cost Rates ---
    "Cpc": Decimal,
    "ECpc": Decimal,
    "ECpm": Decimal,
    "CostPerVisit": Decimal,
    "CostPerVisitPV1D": Decimal,
    "CostPerQualifiedVisit": Decimal,
    # --- Dynamic Rate/Currency Metric Groups (All Decimals) ---
    **dict.fromkeys(
        [
            "RevenueGeneratedClientAttribution",
            "RevenueGeneratedAllClientAttribution",
            "RevenueGeneratedPc30d",
            "RevenueGeneratedAllPc30d",
            "RevenueGeneratedPv24h",
            "RevenueGeneratedAllPv24h",
            "RevenueGeneratedPc30dPv24h",
            "RevenueGeneratedAllPc30dPv24h",
            "RevenueGeneratedPc1d",
            "RevenueGeneratedAllPc1d",
            "RevenueGeneratedPc7d",
            "RevenueGeneratedAllPc7d",
            "RevenueGeneratedPc30Pv24",
            "RevenueGeneratedAllPc30Pv24",
            "RevenueGeneratedPc7dPv24",
            "RevenueGeneratedAllPc7dPv24",
            "RevenueGeneratedLc",
            "RevenueGeneratedAllLc",
            "RevenueGeneratedOfflinePc",
            "RevenueGeneratedOfflinePv",
            "RevenueGeneratedOfflinePc30d",
            "RevenueGeneratedOfflinePv24h",
            "OmnichannelRevenuePc30d",
            "OmnichannelRevenueAllPc30d",
            "OmnichannelRevenuePv24h",
            "OmnichannelRevenueAllPv24h",
            "OmnichannelRevenueClientAttribution",
            "OrderValuePi",
            "PostInstallOrderValue",
            "AdvertiserValue",
            "AdvertiserAllValue",
            "CostOfAdvertiserValue",
            "CostOfAdvertiserValueAll",
        ],
        Decimal,
    ),
    **dict.fromkeys(
        [
            "RoasPc30d",
            "RoasAllPc30d",
            "RoasPv24h",
            "RoasAllPv24h",
            "RoasPc7d",
            "RoasAllPc7d",
            "RoasPc1d",
            "RoasAllPc1d",
            "RoasPc30dPv24h",
            "RoasAllPc30dPv24h",
            "RoasPc30Pv24",
            "RoasAllPc30Pv24",
            "RoasPc7dPv24",
            "RoasAllPc7dPv24",
            "RoasClientAttribution",
            "RoasAllClientAttribution",
            "RoasPc30dClientAttribution",
            "RoasAllPc30dClientAttribution",
            "OmnichannelRoasPc30d",
            "OmnichannelRoasAllPc30d",
            "OmnichannelRoasPv24h",
            "OmnichannelRoasAllPv24h",
            "OmnichannelRoasClientAttribution",
            "PostInstallRoas",
            "RoasOfflinePc30d",
            "RoasOfflinePv24h",
            "ReturnOnAdvertisingSpendingClientAttribution",
            "ReturnOnAdvertisingSpendingAllClientAttribution",
            "ReturnOnAdvertiserSpendingPi",
            "ReturnOnAdvertiserSpendingOfflinePc",
            "ReturnOnAdvertiserSpendingOfflinePv",
        ],
        Decimal,
    ),
    **dict.fromkeys(
        [
            "CostPerOrderPc30d",
            "CostPerOrderAllPc30d",
            "CostPerOrderPv24h",
            "CostPerOrderAllPv24h",
            "CostPerOrderPc7d",
            "CostPerOrderAllPc7d",
            "CostPerOrderPc1d",
            "CostPerOrderAllPc1d",
            "CostPerOrderPc30dPv24h",
            "CostPerOrderAllPc30dPv24h",
            "CostPerOrderPc30Pv24",
            "CostPerOrderAllPc30Pv24",
            "CostPerOrderPc7dPv24",
            "CostPerOrderAllPc7dPv24",
            "CostPerOrderClientAttribution",
            "CostPerOrderAllClientAttribution",
            "CostPerOrderPc30dClientAttribution",
            "CostPerOrderAllPc30dClientAttribution",
            "CostPerOrderPi",
            "PostInstallCostPerOrder",
        ],
        Decimal,
    ),
    **dict.fromkeys(
        [
            "ConversionRatePc30d",
            "ConversionRateAllPc30d",
            "ConversionRatePv24h",
            "ConversionRateAllPv24h",
            "ConversionRatePc7d",
            "ConversionRateAllPc7d",
            "ConversionRatePc1d",
            "ConversionRateAllPc1d",
            "ConversionRatePc30dPv24h",
            "ConversionRateAllPc30dPv24h",
            "ConversionRatePc30Pv24",
            "ConversionRateAllPc30Pv24",
            "ConversionRatePc7dPv24",
            "ConversionRateAllPc7dPv24",
            "ConversionRateClientAttribution",
            "ConversionRateAllClientAttribution",
            "ConversionRatePc30dClientAttribution",
            "ConversionRateAllPc30dClientAttribution",
            "ConversionRatePiPcPv",
            "PostInstallConversionRate",
        ],
        Decimal,
    ),
    **dict.fromkeys(
        [
            "ECosPc30d",
            "ECosAllPc30d",
            "ECosPv24h",
            "ECosAllPv24h",
            "ECosPc7d",
            "ECosAllPc7d",
            "ECosPc1d",
            "ECosAllPc1d",
            "ECosPc30dPv24h",
            "ECosAllPc30dPv24h",
            "ECosPc30Pv24",
            "ECosAllPc30Pv24",
            "ECosPc7dPv24",
            "ECosAllPc7dPv24",
            "ECosClientAttribution",
            "ECosAllClientAttribution",
            "ECosPc30dClientAttribution",
            "ECosAllPc30dClientAttribution",
            "CostOfSalePi",
            "PostInstallCostOfSale",
        ],
        Decimal,
    ),
    **dict.fromkeys(
        [
            "AverageCartPc30d",
            "AverageCartAllPc30d",
            "AverageCartPv24h",
            "AverageCartAllPv24h",
            "AverageCartPc7d",
            "AverageCartAllPc7d",
            "AverageCartPc1d",
            "AverageCartAllPc1d",
            "AverageCartPc30dPv24h",
            "AverageCartAllPc30dPv24h",
            "AverageCartPc30Pv24",
            "AverageCartAllPc30Pv24",
            "AverageCartPc7dPv24",
            "AverageCartAllPc7dPv24",
            "AverageCartClientAttribution",
            "AverageCartAllClientAttribution",
            "AverageCartPc30dClientAttribution",
            "AverageCartAllPc30dClientAttribution",
        ],
        Decimal,
    ),
    **dict.fromkeys(
        [
            "CacPc30d",
            "CacPv24h",
            "CacPc7d",
            "CacPc1d",
            "CacPv7d",
            "CacPv14d",
            "CacPv30d",
            "CacPc30Pv24h",
            "CacPc7dPv24h",
            "CacLc30d",
            "CacClientAttribution",
        ],
        Decimal,
    ),
    # --- Dynamic Sales Metric Groups (All Integers) ---
    **dict.fromkeys(
        [
            "SalesClientAttribution",
            "SalesAllClientAttribution",
            "SalesPc30d",
            "SalesAllPc30d",
            "SalesPv24h",
            "SalesAllPv24h",
            "SalesPc30dPv24h",
            "SalesAllPc30dPv24h",
            "SalesPc1d",
            "SalesAllPc1d",
            "SalesPc7d",
            "SalesAllPc7d",
            "SalesPc30Pv24",
            "SalesAllPc30Pv24",
            "SalesPc7dPv24",
            "SalesAllPc7dPv24",
            "SalesLc",
            "SalesAllLc",
            "SalesPiPc",
            "SalesPiPv",
            "SalesPiPcPv",
            "PostInstallSales",
            "SalesOfflinePc",
            "SalesOfflinePv",
            "SalesOfflinePc30d",
            "SalesOfflinePv24h",
            "SalesPc30dClientAttribution",
            "SalesAllPc30dClientAttribution",
            "OmnichannelSalesPc30d",
            "OmnichannelSalesAllPc30d",
            "OmnichannelSalesPv24h",
            "OmnichannelSalesAllPv24h",
            "OmnichannelSalesClientAttribution",
        ],
        int,
    ),
}
